package com.google.gwt.ddmvc.event;

/**
 * AppEvents represent events which can occur in the application, either
 * low-level events generated by views like the clicking of a button, or
 * higher-level events generated by other controllers representing some
 * translated action.
 * 
 * Events can be subscribed to by controllers, which will be called once
 * as an event has been generated.  For optimization of rendering, events are 
 * processed in the run-loop.
 * 
 * It is not necessary in the implementation of your app-events that you
 * explicitly set the source, as this will be accomplished within the
 * EventSource class.  Also, once the source has been set, it cannot be set
 * to anything else.
 */
public abstract class AppEvent {

	private EventSource source;
	
	public AppEvent() {
		source = null;
	}

	public EventSource getSource() {
		return source;
	}
	
	/**
	 * Set the source of the event to source.
	 * Note - this will have no effect if the source has already been set.
	 * @param source - the source of the event
	 */
	public void setSource(EventSource source) {
		if(this.source == null)
			this.source = source;
	}
	
}
